In [2]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import sklearn
import pickle

In [3]:
df = pd.read_csv('multi_regression_dataset.csv')
df.head()

   Marketing_Spend  Employee_Count  Customer_Satisfaction  Monthly_Revenue
0           218.54               9                      7           326.58
1           477.82              19                      7           604.17
2           379.40               6                      6           393.69
3           319.40               7                      4           369.04
4           120.21               9                      6           230.34

In [4]:
df.isnull().sum()

Marketing_Spend          0
Employee_Count           0
Customer_Satisfaction    0
Monthly_Revenue          0
dtype: int64

In [5]:
x = df.drop(columns = 'Monthly_Revenue')
y = df['Monthly_Revenue']

In [9]:
x.head()

   Marketing_Spend  Employee_Count  Customer_Satisfaction
0           218.54               9                      7
1           477.82              19                      7
2           379.40               6                      6
3           319.40               7                      4
4           120.21               9                      6

In [10]:
y.head()

0    326.58
1    604.17
2    393.69
3    369.04
4    230.34
Name: Monthly_Revenue, dtype: float64

In [6]:
df['Employee_Count'].unique()

array([ 9, 19,  6,  7, 15, 17, 13,  4, 12,  8, 14,  3, 11,  5, 10, 18],
      dtype=int64)

In [7]:
x = pd.get_dummies(x, columns = ['Employee_Count'], drop_first = True)
x.head()

,Marketing_Spend,Customer_Satisfaction,Employee_Count_4,Employee_Count_5,Employee_Count_6,Employee_Count_7,Employee_Count_8,Employee_Count_9,Employee_Count_10,Employee_Count_11,Employee_Count_12,Employee_Count_13,Employee_Count_14,Employee_Count_15,Employee_Count_17,Employee_Count_18,Employee_Count_19
0,218.54,7,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False
1,477.82,7,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True
2,379.40,6,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False
3,319.40,4,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False
4,120.21,6,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False

In [8]:
from sklearn.preprocessing import RobustScaler
scaler = RobustScaler()

x[['Marketing_Spend', 'Customer_Satisfaction']] = scaler.fit_transform(x[['Marketing_Spend', 'Customer_Satisfaction']])
x.head()

,Marketing_Spend,Customer_Satisfaction,Employee_Count_4,Employee_Count_5,Employee_Count_6,Employee_Count_7,Employee_Count_8,Employee_Count_9,Employee_Count_10,Employee_Count_11,Employee_Count_12,Employee_Count_13,Employee_Count_14,Employee_Count_15,Employee_Count_17,Employee_Count_18,Employee_Count_19
0,-0.166872,0.5,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False
1,0.906074,0.5,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True
2,0.498795,0.0,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False
3,0.250504,-1.0,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False
4,-0.573778,0.0,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False

In [9]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.2,random_state=102)

In [10]:
x_train

,Marketing_Spend,Customer_Satisfaction,Employee_Count_4,Employee_Count_5,Employee_Count_6,Employee_Count_7,Employee_Count_8,Employee_Count_9,Employee_Count_10,Employee_Count_11,Employee_Count_12,Employee_Count_13,Employee_Count_14,Employee_Count_15,Employee_Count_17,Employee_Count_18,Employee_Count_19
1,0.906074,0.5,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True
62,0.678929,-1.0,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False
5,-0.573820,-1.0,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False
41,0.057790,-1.0,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False
19,-0.322012,0.0,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
72,-0.854057,-1.0,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
73,0.654225,-1.0,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False
66,-0.601877,-0.5,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False
78,-0.196791,-0.5,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False
0,-0.166872,0.5,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False

In [11]:
y_train

1     604.17
62    522.95
5     256.69
41    338.38
19    243.97
       ...
72    125.19
73    443.45
66    240.97
78    346.26
0     326.58
Name: Monthly_Revenue, Length: 80, dtype: float64

In [22]:
x_test

,Marketing_Spend,Customer_Satisfaction,Employee_Count_4,Employee_Count_5,Employee_Count_6,Employee_Count_7,Employee_Count_8,Employee_Count_9,Employee_Count_10,Employee_Count_11,Employee_Count_12,Employee_Count_13,Employee_Count_14,Employee_Count_15,Employee_Count_17,Employee_Count_18,Employee_Count_19
98,-0.816979,1.0,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True
46,-0.283858,0.0,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False
97,-0.068176,-0.5,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False
21,-0.604566,-1.0,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False
44,-0.382429,1.0,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True
33,0.902681,-1.0,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False
75,0.493208,0.0,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False
65,0.146264,0.0,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False
83,-0.745968,0.5,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True
15,-0.522796,0.5,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False
51,0.579117,-1.0,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False
26,-0.492505,0.0,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False
52,0.885176,1.0,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False
61,-0.359007,-0.5,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False
11,0.941828,1.0,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False
58,-0.780108,1.0,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False
94,0.571378,-0.5,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False
29,-0.777832,-0.5,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
48,0.153754,-1.0,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
57,-0.499374,1.0,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False

In [23]:
y_test

98    257.09
46    295.66
97    384.41
21    238.36
44    369.52
33    490.29
75    462.33
65    355.75
83    277.46
15    282.35
51    453.63
26    267.30
52    557.15
61    304.09
11    524.38
58    195.38
94    500.39
29    195.19
48    336.80
57    258.19
Name: Monthly_Revenue, dtype: float64

In [12]:
from sklearn.linear_model import LinearRegression
lr = LinearRegression()
model = lr.fit(x_train,y_train)
model

LinearRegression()

In [13]:
y_pred = lr.predict(x_test)
y_pred

array([288.38942452, 260.98794678, 336.50688466, 236.92014814,
       373.64623329, 528.24181972, 450.90005995, 374.05725051,
       285.83584438, 290.95940266, 457.69312488, 257.50731784,
       552.00004027, 313.16573825, 534.43362594, 196.59712754,
       495.70348052, 157.1284616 , 323.41600088, 273.90379198])

In [14]:
train_acc = lr.predict(x_train)

In [15]:
from sklearn.metrics import r2_score
r2_score(y_test,y_pred)

0.9634547070460386

In [19]:
print(scaler.transform([[218, 7]]))

[[-0.16910646  0.5       ]]

c:\Python312\Lib\site-packages\sklearn\utils\validation.py:2739: UserWarning: X does not have valid feature names, but RobustScaler was fitted with feature names
  warnings.warn(

In [32]:
pickle.dump(lr,open('multiple linear model.pkl','wb'))